### ISSUE TITLE
[IDEA] Hydratation

### ISSUE THREAD

**Issue by ElGigi** [atlasphp/Atlas.Transit#11]
Hi,

I just look this GIST : https://gist.github.com/ChubV/7fdef280ad016ae61b29#file-hydrate-php
And i think that's would be a good idea to transpose that in Transit to hydrate Domain class instead of constructor.

Regards,
ElGigi

**Comment by pmjones** [comment]
I've thought about this kind of thing; the question then becomes, how do you create a Domain object without a hydrator?  I'd like to be able to set up tests (etc) for the Domain as a self-contained set of objects, without consideration for how they get back and forth from persistence. A constructor is the normal, typical thing to do for that. Do you kind of get what I mean there?

**Comment by froschdesign** [comment]
@ElGigi 
This example is the same as using the `ReflectionClass`, changing the access to a class property and setting a value.

@pmjones 
> I'd like to be able to set up tests (etc) for the Domain as a self-contained set of objects…

These objects must be created completely and correctly without the need for a hydrator or Transit or any other third-party library in general. Everything else means we have designed our objects for a framework or library.

**Comment by pmjones** [comment]
"Everything else means we have designed our objects for a framework or library." Hear hear!

**Comment by ElGigi** [comment]
@pmjones @froschdesign ; I understand your concept.
Let me explain you my ideas and what i imagine (three approaches):

# Interface

First approach ; like \Serializable interface (http://php.net/manual/class.serializable.php) it could be imagine to create a "Transitable" interface with two methods, one to accept data from mapper, and another one to export an array intended to the Mapper.
For the relationships objects, the idea would be to create the children domain objects before and transmit to their parent with the interface.

So it would be simple to get the data from the domain objects and make relation with mapper data.

Frameworks and libraries keep the paternity on the domain objects, and constructors would be intended to initialize the object. And it's very simple to test objects.

The inconvenient, it's how manage the not initialized relationship objects?

# Main entity

Second approach ; create a main entity (a class of the Transit project) who contains the mapper object and domain object. The main entity would contain the magic method __call() ; all methods called would be transmitted to the domain object and analyzed.

If a relation object is not previously gotten, the job of __call() method would be to call mapper to complete domain object and returns the value.

This approach is not easy to test, but she can combined with the first.

# Extend domain class

Third approach ; it's create an anonymous class who would extend the domain class.
This anonymous class, would use a trait to use mapper.

It would be necessary to create methods with the same name of the getters of relationships objects to do the same job that the second approach (get the parent method value, and analyze the result to determine if she is initialized, else call mapper to initialize).

The advantage of this approach it's that the created class would be compatible with the is_a() / instance of / ... tests. Without forget the dynamic to get relationship objects...

Like the second approach, it is not easy to test.

**Comment by froschdesign** [comment]
@ElGigi 
1. All three suggestions have the same problem:

> …we have designed our objects for a framework or library.

2. I'm sorry, but maybe I don't understand the motivation of this issue report / feature request. Do you see any problems in the current implementation or do you dislike something?
